/*
 * Generated by dtrace(8).
 */

#ifndef	_PYDTRACE_PROBES_H
#define	_PYDTRACE_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	PyDTrace_AUDIT(arg0, arg1) \
	__dtrace_python___audit(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_AUDIT_ENABLED() \
	__dtraceenabled_python___audit()
#else
#define	PyDTrace_AUDIT_ENABLED() \
	__dtraceenabled_python___audit(0)
#endif
#define	PyDTrace_FUNCTION_ENTRY(arg0, arg1, arg2) \
	__dtrace_python___function__entry(arg0, arg1, arg2)
#ifndef	__sparc
#define	PyDTrace_FUNCTION_ENTRY_ENABLED() \
	__dtraceenabled_python___function__entry()
#else
#define	PyDTrace_FUNCTION_ENTRY_ENABLED() \
	__dtraceenabled_python___function__entry(0)
#endif
#define	PyDTrace_FUNCTION_RETURN(arg0, arg1, arg2) \
	__dtrace_python___function__return(arg0, arg1, arg2)
#ifndef	__sparc
#define	PyDTrace_FUNCTION_RETURN_ENABLED() \
	__dtraceenabled_python___function__return()
#else
#define	PyDTrace_FUNCTION_RETURN_ENABLED() \
	__dtraceenabled_python___function__return(0)
#endif
#define	PyDTrace_GC_DONE(arg0) \
	__dtrace_python___gc__done(arg0)
#ifndef	__sparc
#define	PyDTrace_GC_DONE_ENABLED() \
	__dtraceenabled_python___gc__done()
#else
#define	PyDTrace_GC_DONE_ENABLED() \
	__dtraceenabled_python___gc__done(0)
#endif
#define	PyDTrace_GC_START(arg0) \
	__dtrace_python___gc__start(arg0)
#ifndef	__sparc
#define	PyDTrace_GC_START_ENABLED() \
	__dtraceenabled_python___gc__start()
#else
#define	PyDTrace_GC_START_ENABLED() \
	__dtraceenabled_python___gc__start(0)
#endif
#define	PyDTrace_IMPORT_FIND_LOAD_DONE(arg0, arg1) \
	__dtrace_python___import__find__load__done(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_IMPORT_FIND_LOAD_DONE_ENABLED() \
	__dtraceenabled_python___import__find__load__done()
#else
#define	PyDTrace_IMPORT_FIND_LOAD_DONE_ENABLED() \
	__dtraceenabled_python___import__find__load__done(0)
#endif
#define	PyDTrace_IMPORT_FIND_LOAD_START(arg0) \
	__dtrace_python___import__find__load__start(arg0)
#ifndef	__sparc
#define	PyDTrace_IMPORT_FIND_LOAD_START_ENABLED() \
	__dtraceenabled_python___import__find__load__start()
#else
#define	PyDTrace_IMPORT_FIND_LOAD_START_ENABLED() \
	__dtraceenabled_python___import__find__load__start(0)
#endif
#define	PyDTrace_INSTANCE_DELETE_DONE(arg0, arg1) \
	__dtrace_python___instance__delete__done(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_INSTANCE_DELETE_DONE_ENABLED() \
	__dtraceenabled_python___instance__delete__done()
#else
#define	PyDTrace_INSTANCE_DELETE_DONE_ENABLED() \
	__dtraceenabled_python___instance__delete__done(0)
#endif
#define	PyDTrace_INSTANCE_DELETE_START(arg0, arg1) \
	__dtrace_python___instance__delete__start(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_INSTANCE_DELETE_START_ENABLED() \
	__dtraceenabled_python___instance__delete__start()
#else
#define	PyDTrace_INSTANCE_DELETE_START_ENABLED() \
	__dtraceenabled_python___instance__delete__start(0)
#endif
#define	PyDTrace_INSTANCE_NEW_DONE(arg0, arg1) \
	__dtrace_python___instance__new__done(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_INSTANCE_NEW_DONE_ENABLED() \
	__dtraceenabled_python___instance__new__done()
#else
#define	PyDTrace_INSTANCE_NEW_DONE_ENABLED() \
	__dtraceenabled_python___instance__new__done(0)
#endif
#define	PyDTrace_INSTANCE_NEW_START(arg0, arg1) \
	__dtrace_python___instance__new__start(arg0, arg1)
#ifndef	__sparc
#define	PyDTrace_INSTANCE_NEW_START_ENABLED() \
	__dtraceenabled_python___instance__new__start()
#else
#define	PyDTrace_INSTANCE_NEW_START_ENABLED() \
	__dtraceenabled_python___instance__new__start(0)
#endif
#define	PyDTrace_LINE(arg0, arg1, arg2) \
	__dtrace_python___line(arg0, arg1, arg2)
#ifndef	__sparc
#define	PyDTrace_LINE_ENABLED() \
	__dtraceenabled_python___line()
#else
#define	PyDTrace_LINE_ENABLED() \
	__dtraceenabled_python___line(0)
#endif


extern void __dtrace_python___audit(char *, void *);
#ifndef	__sparc
extern int __dtraceenabled_python___audit(void);
#else
extern int __dtraceenabled_python___audit(long);
#endif
extern void __dtrace_python___function__entry(char *, char *, int);
#ifndef	__sparc
extern int __dtraceenabled_python___function__entry(void);
#else
extern int __dtraceenabled_python___function__entry(long);
#endif
extern void __dtrace_python___function__return(char *, char *, int);
#ifndef	__sparc
extern int __dtraceenabled_python___function__return(void);
#else
extern int __dtraceenabled_python___function__return(long);
#endif
extern void __dtrace_python___gc__done(long);
#ifndef	__sparc
extern int __dtraceenabled_python___gc__done(void);
#else
extern int __dtraceenabled_python___gc__done(long);
#endif
extern void __dtrace_python___gc__start(int);
#ifndef	__sparc
extern int __dtraceenabled_python___gc__start(void);
#else
extern int __dtraceenabled_python___gc__start(long);
#endif
extern void __dtrace_python___import__find__load__done(char *, int);
#ifndef	__sparc
extern int __dtraceenabled_python___import__find__load__done(void);
#else
extern int __dtraceenabled_python___import__find__load__done(long);
#endif
extern void __dtrace_python___import__find__load__start(char *);
#ifndef	__sparc
extern int __dtraceenabled_python___import__find__load__start(void);
#else
extern int __dtraceenabled_python___import__find__load__start(long);
#endif
extern void __dtrace_python___instance__delete__done(char *, char *);
#ifndef	__sparc
extern int __dtraceenabled_python___instance__delete__done(void);
#else
extern int __dtraceenabled_python___instance__delete__done(long);
#endif
extern void __dtrace_python___instance__delete__start(char *, char *);
#ifndef	__sparc
extern int __dtraceenabled_python___instance__delete__start(void);
#else
extern int __dtraceenabled_python___instance__delete__start(long);
#endif
extern void __dtrace_python___instance__new__done(char *, char *);
#ifndef	__sparc
extern int __dtraceenabled_python___instance__new__done(void);
#else
extern int __dtraceenabled_python___instance__new__done(long);
#endif
extern void __dtrace_python___instance__new__start(char *, char *);
#ifndef	__sparc
extern int __dtraceenabled_python___instance__new__start(void);
#else
extern int __dtraceenabled_python___instance__new__start(long);
#endif
extern void __dtrace_python___line(char *, char *, int);
#ifndef	__sparc
extern int __dtraceenabled_python___line(void);
#else
extern int __dtraceenabled_python___line(long);
#endif

#else

#define	PyDTrace_AUDIT(arg0, arg1)
#define	PyDTrace_AUDIT_ENABLED() (0)
#define	PyDTrace_FUNCTION_ENTRY(arg0, arg1, arg2)
#define	PyDTrace_FUNCTION_ENTRY_ENABLED() (0)
#define	PyDTrace_FUNCTION_RETURN(arg0, arg1, arg2)
#define	PyDTrace_FUNCTION_RETURN_ENABLED() (0)
#define	PyDTrace_GC_DONE(arg0)
#define	PyDTrace_GC_DONE_ENABLED() (0)
#define	PyDTrace_GC_START(arg0)
#define	PyDTrace_GC_START_ENABLED() (0)
#define	PyDTrace_IMPORT_FIND_LOAD_DONE(arg0, arg1)
#define	PyDTrace_IMPORT_FIND_LOAD_DONE_ENABLED() (0)
#define	PyDTrace_IMPORT_FIND_LOAD_START(arg0)
#define	PyDTrace_IMPORT_FIND_LOAD_START_ENABLED() (0)
#define	PyDTrace_INSTANCE_DELETE_DONE(arg0, arg1)
#define	PyDTrace_INSTANCE_DELETE_DONE_ENABLED() (0)
#define	PyDTrace_INSTANCE_DELETE_START(arg0, arg1)
#define	PyDTrace_INSTANCE_DELETE_START_ENABLED() (0)
#define	PyDTrace_INSTANCE_NEW_DONE(arg0, arg1)
#define	PyDTrace_INSTANCE_NEW_DONE_ENABLED() (0)
#define	PyDTrace_INSTANCE_NEW_START(arg0, arg1)
#define	PyDTrace_INSTANCE_NEW_START_ENABLED() (0)
#define	PyDTrace_LINE(arg0, arg1, arg2)
#define	PyDTrace_LINE_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _PYDTRACE_PROBES_H */
