/* This file is automatically generated.
   It defines macros to allow user program to find the shared
   library files which come as part of GNU libc.  */
#ifndef __GNU_LIB_NAMES_H
#define __GNU_LIB_NAMES_H	1

#include <bits/wordsize.h>

#if defined __loongarch_lp64
# include <gnu/lib-names-lp64.h>
#endif

#endif	/* gnu/lib-names.h */
