/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RQUOTA_H_RPCGEN
#define	_RQUOTA_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define	RQ_PATHLEN 1024

struct getquota_args {
	char *gqa_pathp;
	int32_t gqa_uid;
};
typedef struct getquota_args getquota_args;

struct rquota {
	int32_t rq_bsize;
	bool_t rq_active;
	uint32_t rq_bhardlimit;
	uint32_t rq_bsoftlimit;
	uint32_t rq_curblocks;
	uint32_t rq_fhardlimit;
	uint32_t rq_fsoftlimit;
	uint32_t rq_curfiles;
	uint32_t rq_btimeleft;
	uint32_t rq_ftimeleft;
};
typedef struct rquota rquota;

enum gqr_status {
	Q_OK = 1,
	Q_NOQUOTA = 2,
	Q_EPERM = 3
};
typedef enum gqr_status gqr_status;

struct getquota_rslt {
	gqr_status status;
	union {
		rquota gqr_rquota;
	} getquota_rslt_u;
};
typedef struct getquota_rslt getquota_rslt;

#define	RQUOTAPROG	100011
#define	RQUOTAVERS	1

#if defined(__STDC__) || defined(__cplusplus)
#define	RQUOTAPROC_GETQUOTA	1
extern  getquota_rslt * rquotaproc_getquota_1(getquota_args *, CLIENT *);
extern  getquota_rslt * rquotaproc_getquota_1_svc(getquota_args *, struct svc_req *);
#define	RQUOTAPROC_GETACTIVEQUOTA	2
extern  getquota_rslt * rquotaproc_getactivequota_1(getquota_args *, CLIENT *);
extern  getquota_rslt * rquotaproc_getactivequota_1_svc(getquota_args *, struct svc_req *);
extern int rquotaprog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	RQUOTAPROC_GETQUOTA	1
extern  getquota_rslt * rquotaproc_getquota_1();
extern  getquota_rslt * rquotaproc_getquota_1_svc();
#define	RQUOTAPROC_GETACTIVEQUOTA	2
extern  getquota_rslt * rquotaproc_getactivequota_1();
extern  getquota_rslt * rquotaproc_getactivequota_1_svc();
extern int rquotaprog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_getquota_args(XDR *, getquota_args*);
extern  bool_t xdr_rquota(XDR *, rquota*);
extern  bool_t xdr_gqr_status(XDR *, gqr_status*);
extern  bool_t xdr_getquota_rslt(XDR *, getquota_rslt*);

#else /* K&R C */
extern bool_t xdr_getquota_args();
extern bool_t xdr_rquota();
extern bool_t xdr_gqr_status();
extern bool_t xdr_getquota_rslt();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RQUOTA_H_RPCGEN */
