/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RWALL_H_RPCGEN
#define	_RWALL_H_RPCGEN

#include <rpc/rpc.h>
#ifndef _KERNEL
#include <synch.h>
#include <thread.h>
#endif /* !_KERNEL */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/* from rwall.x */

/*
 * Remote write-all ONC service
 */


typedef char *wrapstring;


#if defined(__STDC__) || defined(__cplusplus)
enum clnt_stat rwall(char *, char *);
#else
enum clnt_stat rwall();
#endif


#define	WALLPROG	100008
#define	WALLVERS	1

#if defined(__STDC__) || defined(__cplusplus)
#define	WALLPROC_WALL	2
extern  enum clnt_stat wallproc_wall_1(wrapstring *, void *, CLIENT *);
extern  bool_t wallproc_wall_1_svc(wrapstring *, void *, struct svc_req *);
extern int wallprog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	WALLPROC_WALL	2
extern  enum clnt_stat wallproc_wall_1();
extern  bool_t wallproc_wall_1_svc();
extern int wallprog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_wrapstring(XDR *, wrapstring*);

#else /* K&R C */
extern bool_t xdr_wrapstring();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RWALL_H_RPCGEN */
